### PR TITLE
Corrections (once again)

### PR DESCRIPTION
**Pull request by shreyjain711**
(Summary after PPS)
Please adhere to the claims made by you in the README.md file ("corrections would be heartily accepted").

PS. Cheap tricks like making the suggested changes in the pull request by yourself is the lowest standard one can fall to. This is totally against the very spirit of Open Source Development. I strongly believe in your devotion for OSD and thus humbly request you to not fall to such low heights. ( #9 )
PPS. The SS of these cheap tricks don't look good on a facebook wall as well. 😜  

Summary:
1. Android 4 was released by the name 'Ice Cream Sandwich' ... not 'Ice Cream Sandwitch'. Please refer to [developer.android.com](developer.android.com) for any further reference
2. Please refer to primary and middle school English grammar for the changes in first paragraph 
 **It's really sad that a Mac can't auto-correct your grammar as well** 😢   
3. 'this' was changed to 'the' due to the simple fact that when a user is looking in your application's README.md file, she/he won't be expecting the description of any other app. 😕 

Any changes in the pull request are invited as long as they are valid and the owner(s) doesn't make the suggested changes (in the pull request) by themselves

### CODE REVIEW

**Comment by mohityv** [comment]
I am sorry since you yourself had pointed out the mistakes and informed me about them so I corrected them before having realised that you had already posted a PR for the same. 😅

**Comment by shreyjain711** [comment]
So you intend to say that you didn't realize that you were looking at a pull request while looking for one in the 'Pull requests' tab, I don't know what else can one expect to find in the 'Pull requests' tab. 

Well I didn't add an issue for the corrections, and the only instance or way through which I conveyed the errors to you was through the pull request. 

# Its really sad how bigoted and ungenerous a person can become. 🙈 
## especially when that person is planning to do open source development 🙊 

### I highly recommend you to edit the README.md to let the viewer know that no spelling or grammar corrections are welcomed. 😄
### No need to make false claims when you can't stand up to them right? 😉

**Comment by mohityv** [comment]
Okay first of all the changes you make in the code or even the readme file are not visible to me unless I have merged your pull request.

**Comment by shreyjain711** [comment]
LoL! There's a 'Changes' tab right under the 'Pull Requests' tab for you to see what all changes I made.

'Braggi' isn't a word😅

**Comment by shreyjain711** [comment]
Closing a correct pull request isn't really going to show you the changes either though. 

Hey, let me tell you about a nice quote I recently read.

People say that accepting mistakes with the will to learn makes the person diligent, but not accepting that they can make mistakes and lying to the one who intended to help them out by humbly telling them about their mistakes makes them....umm... not so wise😅

Getting more stars isn't going to help your project much but acknowledging and appreciating even the smallest help from someone would definitely do.

Sorry if my humble suggestions hurt you in any manner, didn't mean to hurt any of your feelings, just wanted to help. I would make sure not to do so again ☺️ Since you don't need anyone's help with the project.

**Pull request closed without merging**
